name: Build and Push Frontend Docker Image to GHCR
on:
  push:
    branches: [main, master,dev]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: ghcr.io/theeye-network/etherx-registration-site
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          VERSION=0.1-${GITHUB_SHA::7}
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION .
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Push
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION

      - name: Notify Jenkins
        run: |
          curl --insecure "${{ secrets.JENKINS_WEBHOOK_URL }}"